/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.adp.java;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AdPlanType implements org.apache.thrift.TBase<AdPlanType, AdPlanType._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AdPlanType");

  private static final org.apache.thrift.protocol.TField TYPE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("type_id", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TYPE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("type_name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CATE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("cate_name", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AdPlanTypeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AdPlanTypeTupleSchemeFactory());
  }

  public int type_id; // required
  public String type_name; // required
  public String cate_name; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TYPE_ID((short)1, "type_id"),
    TYPE_NAME((short)2, "type_name"),
    CATE_NAME((short)3, "cate_name");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE_ID
          return TYPE_ID;
        case 2: // TYPE_NAME
          return TYPE_NAME;
        case 3: // CATE_NAME
          return CATE_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TYPE_ID_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE_ID, new org.apache.thrift.meta_data.FieldMetaData("type_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TYPE_NAME, new org.apache.thrift.meta_data.FieldMetaData("type_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CATE_NAME, new org.apache.thrift.meta_data.FieldMetaData("cate_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AdPlanType.class, metaDataMap);
  }

  public AdPlanType() {
  }

  public AdPlanType(
    int type_id,
    String type_name,
    String cate_name)
  {
    this();
    this.type_id = type_id;
    setType_idIsSet(true);
    this.type_name = type_name;
    this.cate_name = cate_name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AdPlanType(AdPlanType other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.type_id = other.type_id;
    if (other.isSetType_name()) {
      this.type_name = other.type_name;
    }
    if (other.isSetCate_name()) {
      this.cate_name = other.cate_name;
    }
  }

  public AdPlanType deepCopy() {
    return new AdPlanType(this);
  }

  @Override
  public void clear() {
    setType_idIsSet(false);
    this.type_id = 0;
    this.type_name = null;
    this.cate_name = null;
  }

  public int getType_id() {
    return this.type_id;
  }

  public AdPlanType setType_id(int type_id) {
    this.type_id = type_id;
    setType_idIsSet(true);
    return this;
  }

  public void unsetType_id() {
    __isset_bit_vector.clear(__TYPE_ID_ISSET_ID);
  }

  /** Returns true if field type_id is set (has been assigned a value) and false otherwise */
  public boolean isSetType_id() {
    return __isset_bit_vector.get(__TYPE_ID_ISSET_ID);
  }

  public void setType_idIsSet(boolean value) {
    __isset_bit_vector.set(__TYPE_ID_ISSET_ID, value);
  }

  public String getType_name() {
    return this.type_name;
  }

  public AdPlanType setType_name(String type_name) {
    this.type_name = type_name;
    return this;
  }

  public void unsetType_name() {
    this.type_name = null;
  }

  /** Returns true if field type_name is set (has been assigned a value) and false otherwise */
  public boolean isSetType_name() {
    return this.type_name != null;
  }

  public void setType_nameIsSet(boolean value) {
    if (!value) {
      this.type_name = null;
    }
  }

  public String getCate_name() {
    return this.cate_name;
  }

  public AdPlanType setCate_name(String cate_name) {
    this.cate_name = cate_name;
    return this;
  }

  public void unsetCate_name() {
    this.cate_name = null;
  }

  /** Returns true if field cate_name is set (has been assigned a value) and false otherwise */
  public boolean isSetCate_name() {
    return this.cate_name != null;
  }

  public void setCate_nameIsSet(boolean value) {
    if (!value) {
      this.cate_name = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TYPE_ID:
      if (value == null) {
        unsetType_id();
      } else {
        setType_id((Integer)value);
      }
      break;

    case TYPE_NAME:
      if (value == null) {
        unsetType_name();
      } else {
        setType_name((String)value);
      }
      break;

    case CATE_NAME:
      if (value == null) {
        unsetCate_name();
      } else {
        setCate_name((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE_ID:
      return Integer.valueOf(getType_id());

    case TYPE_NAME:
      return getType_name();

    case CATE_NAME:
      return getCate_name();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TYPE_ID:
      return isSetType_id();
    case TYPE_NAME:
      return isSetType_name();
    case CATE_NAME:
      return isSetCate_name();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AdPlanType)
      return this.equals((AdPlanType)that);
    return false;
  }

  public boolean equals(AdPlanType that) {
    if (that == null)
      return false;

    boolean this_present_type_id = true;
    boolean that_present_type_id = true;
    if (this_present_type_id || that_present_type_id) {
      if (!(this_present_type_id && that_present_type_id))
        return false;
      if (this.type_id != that.type_id)
        return false;
    }

    boolean this_present_type_name = true && this.isSetType_name();
    boolean that_present_type_name = true && that.isSetType_name();
    if (this_present_type_name || that_present_type_name) {
      if (!(this_present_type_name && that_present_type_name))
        return false;
      if (!this.type_name.equals(that.type_name))
        return false;
    }

    boolean this_present_cate_name = true && this.isSetCate_name();
    boolean that_present_cate_name = true && that.isSetCate_name();
    if (this_present_cate_name || that_present_cate_name) {
      if (!(this_present_cate_name && that_present_cate_name))
        return false;
      if (!this.cate_name.equals(that.cate_name))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(AdPlanType other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    AdPlanType typedOther = (AdPlanType)other;

    lastComparison = Boolean.valueOf(isSetType_id()).compareTo(typedOther.isSetType_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type_id, typedOther.type_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType_name()).compareTo(typedOther.isSetType_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type_name, typedOther.type_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCate_name()).compareTo(typedOther.isSetCate_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCate_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cate_name, typedOther.cate_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AdPlanType(");
    boolean first = true;

    sb.append("type_id:");
    sb.append(this.type_id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("type_name:");
    if (this.type_name == null) {
      sb.append("null");
    } else {
      sb.append(this.type_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("cate_name:");
    if (this.cate_name == null) {
      sb.append("null");
    } else {
      sb.append(this.cate_name);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AdPlanTypeStandardSchemeFactory implements SchemeFactory {
    public AdPlanTypeStandardScheme getScheme() {
      return new AdPlanTypeStandardScheme();
    }
  }

  private static class AdPlanTypeStandardScheme extends StandardScheme<AdPlanType> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AdPlanType struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type_id = iprot.readI32();
              struct.setType_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TYPE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.type_name = iprot.readString();
              struct.setType_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CATE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.cate_name = iprot.readString();
              struct.setCate_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AdPlanType struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TYPE_ID_FIELD_DESC);
      oprot.writeI32(struct.type_id);
      oprot.writeFieldEnd();
      if (struct.type_name != null) {
        oprot.writeFieldBegin(TYPE_NAME_FIELD_DESC);
        oprot.writeString(struct.type_name);
        oprot.writeFieldEnd();
      }
      if (struct.cate_name != null) {
        oprot.writeFieldBegin(CATE_NAME_FIELD_DESC);
        oprot.writeString(struct.cate_name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AdPlanTypeTupleSchemeFactory implements SchemeFactory {
    public AdPlanTypeTupleScheme getScheme() {
      return new AdPlanTypeTupleScheme();
    }
  }

  private static class AdPlanTypeTupleScheme extends TupleScheme<AdPlanType> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AdPlanType struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetType_id()) {
        optionals.set(0);
      }
      if (struct.isSetType_name()) {
        optionals.set(1);
      }
      if (struct.isSetCate_name()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetType_id()) {
        oprot.writeI32(struct.type_id);
      }
      if (struct.isSetType_name()) {
        oprot.writeString(struct.type_name);
      }
      if (struct.isSetCate_name()) {
        oprot.writeString(struct.cate_name);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AdPlanType struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.type_id = iprot.readI32();
        struct.setType_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.type_name = iprot.readString();
        struct.setType_nameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.cate_name = iprot.readString();
        struct.setCate_nameIsSet(true);
      }
    }
  }

}

