/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.adp.java;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AuditStatus implements org.apache.thrift.TEnum {
  READY_TO_AUDIT(1),
  PASS_TO_AUDIT(2),
  FAILED_TO_AUDIT(3);

  private final int value;

  private AuditStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AuditStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return READY_TO_AUDIT;
      case 2:
        return PASS_TO_AUDIT;
      case 3:
        return FAILED_TO_AUDIT;
      default:
        return null;
    }
  }
}
