/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.adp.java;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CurrencyType implements org.apache.thrift.TEnum {
  RMB(1),
  EUR(2),
  USA(3);

  private final int value;

  private CurrencyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CurrencyType findByValue(int value) { 
    switch (value) {
      case 1:
        return RMB;
      case 2:
        return EUR;
      case 3:
        return USA;
      default:
        return null;
    }
  }
}
