/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.adp.java;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum NetWorkType implements org.apache.thrift.TEnum {
  HARD_LINK(1),
  MOBILE_LINK(2);

  private final int value;

  private NetWorkType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NetWorkType findByValue(int value) { 
    switch (value) {
      case 1:
        return HARD_LINK;
      case 2:
        return MOBILE_LINK;
      default:
        return null;
    }
  }
}
