/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.adp.java;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum PlanStatus implements org.apache.thrift.TEnum {
  RUNNING(1),
  STOPPED(2),
  EXPIRED(3),
  DELETED(4),
  FROZEN(5);

  private final int value;

  private PlanStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static PlanStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return RUNNING;
      case 2:
        return STOPPED;
      case 3:
        return EXPIRED;
      case 4:
        return DELETED;
      case 5:
        return FROZEN;
      default:
        return null;
    }
  }
}
