/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.adp.java;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ReleaseType implements org.apache.thrift.TEnum {
  AD_BRAND(1),
  LONG_TAIL(2),
  AD_DEFAULT(3);

  private final int value;

  private ReleaseType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReleaseType findByValue(int value) { 
    switch (value) {
      case 1:
        return AD_BRAND;
      case 2:
        return LONG_TAIL;
      case 3:
        return AD_DEFAULT;
      default:
        return null;
    }
  }
}
